

var papers = {
pfn : { // paper format names;
    A: ['A0', 'A1','A2', 'A3', 'A4', 'A5', 'A6'],
    B: ['B0', 'B1', 'B2', 'B3', 'B4', 'B5', 'B6'],
    SRA: ['','','','SRA3', 'SRA4','',''],
    EP: ['EP0','EP1','EP2', 'EP3', 'EP4', 'EP5', 'EP6'], // ePrintare format names
    CF: ['mucavaCD_sina', 'mucavaSpateCD_surub', 'mucavaGauriCD_surub']  // custom format names
    },
d : { // paper dimensions
    um: 'mm',
    A: [[841, 1189],[594, 841],[420, 594],[297, 420],[210, 297],[148, 210],[105, 148]], // A0, A1, A2, A3, A4, A5, A6
    B: [[1000, 1414],[707, 1000],[500, 707],[353, 500],[250, 353],[176, 250],[125, 176]], // B0, ***B1***, B2, B3, B4, B5, B6
    SRA: [[],[],[],[],[],[],[]],
    EP: [[],[],[],[],[210, 330],[],[]], // ePrintare format
    CF: [[200, 303],[190, 303],[20, 303]],
    tk: [3, 2.5, 2.2, 2, 0.5, 0.03], // tickness (grosimea hartiei)
    },
pt : [ // paper type;
     'plain',
     'matt',
     'gloss',
     'color specific',
     'double coated offset',
     'cardboard', // (mucava)
     'sticker' // (autocolant)
    ],
weight : { // paper density; (weigth)
    um: 'g/mp',
    od: [60, 90, 115, 130, 150, 170, 200, 250, 300, 350], // offset densities
    pd: [80, 90], // plain densities
    csd: [90, 120, 160, 200, 300] // color specific densities
    },
psn : [ // paper supplier name;
    'Digital printing paper',
    'Quatro gloss',
    'Color Copy',
    ]   
 };

var paper = {
    name: String,
    supplierName: String,
    type: String, // 'offset-matt', 'offset-gloss', 'color copy', 'plain', 'sticker matt (autocolant mat)'
    density: Number, // 90g/mp, 115g/mp
    width: Number, // (latime)
    length: Number, // (lungime)
    tikness: Number,
    
    };


// should be generated by Function.apply(ob, [args, args]) or new call constructor of Function();
var pf = { // paper format;
    um: 'mm',
    A3: {
        name: 'A3', 
        w: 297, // width
        l: 420
            }, // length
    A4: {
        name: 'A4', 
        w: 210, 
        l: 297
            }, 
    A5: {
        name: 'A5', 
        w: 148.5, 
        l: 210
            },
    };

 var PF = function (name, d) { // paper format constructor; d= []
     this.name = 'format ' + name;
     if (d[0]<d[1]) {
         this.width = d[0];
         this.length = d[1];
         } else {
             this.width = d[1];
             this.length = d[0];
             }
     };
 var A4_format = new PF (papers.pfn.A[4], papers.d.A[4]);
 